import { Inject, Injectable, Logger } from '@nestjs/common';
import { CORE_CONFIG } from '../config';
import type { CoreConfig } from '../config';
import type { MemoryCandidate } from '../memory/memory-candidate';
import { ClaimVerifierService } from './claim-verifier.service';
import { HallucinationMitigationService } from './hallucination-mitigation.service';
import { describeAssertion } from './hallucination.types';
import type { ClaimAssertion } from './hallucination.types';

/**
 * Turn-time hallucination audit (M15.5e wiring).
 *
 * The reply is generated by the chat model; the extraction ledger then
 * carries the turn's mined triples, each stamped with the side it came
 * from. The **assistant-sourced** ones are the claims the model asserted —
 * those are what we check against the store and (for high-stakes ones) put
 * to a verifier, then turn into an explicit, logged mitigation.
 *
 * It runs in the post-turn enrichment path (fire-and-forget, like
 * extraction and promotion): it never blocks or fails a turn. This is the
 * audit shape; blocking pre-send mitigation is a separate slice.
 */
@Injectable()
export class HallucinationGuardService {
  private readonly logger = new Logger(HallucinationGuardService.name);

  constructor(
    @Inject(CORE_CONFIG) private readonly config: CoreConfig,
    private readonly verifier: ClaimVerifierService,
    private readonly mitigation: HallucinationMitigationService,
  ) {}

  /** Audit a turn's candidates; returns how many claims were mitigated. */
  async audit(candidates: readonly MemoryCandidate[]): Promise<number> {
    let mitigated = 0;
    for (const candidate of candidates) {
      // Only the model's own assertions are the model's to answer for.
      if (candidate.source.role !== 'assistant') {
        continue;
      }
      const assertion: ClaimAssertion = {
        subject: candidate.subject,
        predicate: candidate.predicate,
        object: candidate.object,
        negated: candidate.negated,
        confidence: candidate.confidence,
      };
      try {
        const result = await this.verifier.verify(
          assertion,
          this.config.llmModel,
        );
        const plan = this.mitigation.plan(result.findings);
        if (plan.strategy === 'none') {
          continue;
        }
        await this.mitigation.record(plan, {
          subject: describeAssertion(assertion),
          detail: {
            candidateId: candidate.id,
            classification: result.classification,
            disagreement: result.disagreement,
            verifier: result.verification.backend,
          },
        });
        mitigated += 1;
      } catch (error) {
        this.logger.warn(
          `Hallucination audit failed for candidate ${candidate.id}: ${
            error instanceof Error ? error.message : 'unknown error'
          }`,
        );
      }
    }
    return mitigated;
  }
}
